#Simple Example for Interaction with Text box by performing Addition,etc 
import tkinter as tk 
def f1(event): 
 s1=t1.get() 
 s2=t2.get() 
 a=int(s1) 
 b=int(s2) 
 c=a+b 
 t3.delete(0,'end') 
 t3.insert(0,c) 
def f2(event): 
 t1.delete(0,'end') 
 t2.delete(0,'end') 
 t3.delete(0,'end') 
root=tk.Tk() 
root.geometry("400x400") 
l1=tk.Label(root,text="1st Number") 
l2=tk.Label(root,text="2nd Number") 
l3=tk.Label(root,text="Result") 
t1=tk.Entry(root,width=30) 
t2=tk.Entry(root,width=30) 
t3=tk.Entry(root,width=30) 
l1.grid(row=0,column=0) 
t1.grid(row=0,column=1) 
l2.grid(row=1,column=0) 
t2.grid(row=1,column=1) 
l3.grid(row=2,column=0) 
t3.grid(row=2,column=1) 
b1=tk.Button(root,text="Addition",width=15) 
b2=tk.Button(root,text="Clear",width=15) 
b1.grid(row=0,column=2) 
b2.grid(row=1,column=2) 
b1.bind("<Button-1>",f1) 
b2.bind("<Button-1>",f2) 
root.mainloop() 
