import tkinter as tk 
w=tk.Tk() 
w.geometry('400x300') 
l1=tk.Label(w,text='Example of Label') 
l1.pack() 
l2=tk.Label(w,text='First Name') 
l2.pack() 
t1=tk.Entry(w,width=40) 
t1.pack() 
b1=tk.Button(w,text="Click Here") 
b1.pack() 
t2=tk.Text(w) 
t2.pack() 
w.mainloop() 